### PR TITLE
Sort dependencies with case insensitive comparison

### PR DESCRIPTION
**Pull request by jystic**
/cc @markhibberd @nhibberd

### CODE REVIEW

**Comment by erikd-ambiata** [comment]
+1

**Comment by nhibberd** [comment]
Looks good, curious any reason for this?

**Comment by jystic** [comment]
> Looks good, curious any reason for this?

Otherwise the output isn't sorted and it make me :sadpanda:

**Comment by tmcgilchrist** [comment]
I don't suppose the order is significant, as in swapping things around won't work.

🔪

**Comment by markhibberd** [comment]
👍

**Pull request merged**
