### PR TITLE
Delete sandbox sources that are no longer being used

### PR DESCRIPTION
**Pull request by charleso**
/cc @markhibberd @michaelneale 

@michaelneale I'm happy to wait for your change first as this will probably need some re-work at that point.

### CODE REVIEW

**Comment by michaelneale** [comment]
ok @charleso I will get mine going first with the suggested changes and then you can look at re-applying it.

**Comment by charleso** [comment]
Have updated and fixed merge conflicts (although will probably have another round after https://github.com/ambiata/cabal-extras/pull/42)

**Comment by michaelneale** [comment]
:tada: (assuming you can re-do it on marks latest changes). 

You may want to also check this works with things like: https://github.com/ambiata/hydra/tree/master/hydra-core where the project is in a sub directory away from the lib (should be ok if git commands I think).

**Comment by charleso** [comment]
Rebased

**Comment by michaelneale** [comment]
:shaved_ice:

**Comment by charleso** [comment]
Merging, please let me know if you see any problems with this.

**Pull request merged**
